### ISSUE TITLE
Problems with google registration callback

### ISSUE THREAD

**Issue by whotopia** [Mordorreal/redmine_document_library_gdrive#2]
I managed to get plugin working to the point of callback to Redmine.  Then I get this:
![screen shot 2016-05-24 at 16 57 29](https://cloud.githubusercontent.com/assets/9039050/15508705/cd698e9c-21d0-11e6-8839-e7434c86bcf5.png)
or 
![screen shot 2016-05-24 at 17 00 42](https://cloud.githubusercontent.com/assets/9039050/15508781/1fa5ee6c-21d1-11e6-975d-23643f9e142a.png)

**Comment by Mordorreal** [comment]
For G+ authorization you need to set right callback in Google Dev Console. I will check today right callback. Thanks for reporting.

**Comment by Mordorreal** [comment]
You need to add http://yourredmine.com/auth/google_oauth2/callback and https://yourredmine.com/auth/google_oauth2/callback as callbacks  in Google Dev console.
Also, please, take a look at updated README.

**Comment by mjmoralesg** [comment]
It happens to me the same error in the declaration of the environment variable I have the following GOOGLE_CLIENT_ID = " xxxxxx.googleusercontent.com "
GOOGLE_CLIENT_SECRET = " xxxx " and add callbacks in Google Dev

![image](https://cloud.githubusercontent.com/assets/19652459/15653736/b267e144-265c-11e6-94a1-7e5655a7b1e4.png)

any suggestions

**Comment by Mordorreal** [comment]
@mjmoralesg Look at url. Error is invalid credentials. Check your Google ID. Usually it's a numbers with letters. Recheck it, please.

**Comment by mjmoralesg** [comment]
Thanks for answering.

this is my configuration

![image](https://cloud.githubusercontent.com/assets/19652459/15654149/ae1b4f42-265f-11e6-8164-bda4869db11d.png)

change application.yml

![image](https://cloud.githubusercontent.com/assets/19652459/15654180/ea7506d6-265f-11e6-9cd8-3ceb67116aae.png)

**Comment by Mordorreal** [comment]
Please, check also that you enable Google+ API in Google Project.

**Comment by mjmoralesg** [comment]
Worked thank you very much
